//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.239
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlyWorko.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int LogoSwitcher {
            get {
                return ((int)(this["LogoSwitcher"]));
            }
            set {
                this["LogoSwitcher"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".\\LogoInfo.log")]
        public string LogoFilo {
            get {
                return ((string)(this["LogoFilo"]));
            }
            set {
                this["LogoFilo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("noHoma")]
        public string Zapuskatel {
            get {
                return ((string)(this["Zapuskatel"]));
            }
            set {
                this["Zapuskatel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\Worka\\Chaso\\engino\\Houdini3Prow32.exe")]
        public string Houdini {
            get {
                return ((string)(this["Houdini"]));
            }
            set {
                this["Houdini"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public string MinoKvo {
            get {
                return ((string)(this["MinoKvo"]));
            }
            set {
                this["MinoKvo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public string ValuiKvo {
            get {
                return ((string)(this["ValuiKvo"]));
            }
            set {
                this["ValuiKvo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Password=Petro;Persist Security Info=True;User ID=Petro;Initial Catalog=Gosoma;Da" +
            "ta Source=vyz7;")]
        public string BidoGamos {
            get {
                return ((string)(this["BidoGamos"]));
            }
            set {
                this["BidoGamos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\..\\..\\GamoAtro.cfg")]
        public string GamoConfigoAtr {
            get {
                return ((string)(this["GamoConfigoAtr"]));
            }
            set {
                this["GamoConfigoAtr"] = value;
            }
        }
    }
}
